### ISSUE TITLE
Updating firmware

### ISSUE THREAD

**Issue by jonnyrider** [hn/ginlong-solis#11]
Sorry for the very basic question, but even though I'm familiar with ESPHome and Home Assistant, I've never actually flashed the firmware on any other device!

My understanding is that I need to connect the S3 wifi stick via a serial adapter to my Raspberry Pi and then I can run the commands in the readme. Will the following adapter work?

https://www.amazon.co.uk/dp/B08CRL6KHV?psc=1&ref=ppx_yo2ov_dt_b_product_details

Do I then attach wires between the stick and the serial adapter (TX to TX, RX to RX and GND to GND)?

![image](https://github.com/hn/ginlong-solis/assets/48350560/29e2eb1b-d7c1-4479-8570-f5f3943a822c)

I understand that I will need to connect the TX pin to GND at boot so the firmware can be flashed.

I then think I just type the code into a terminal on the Pi and the stick will be updated with ESPHome firmware that will provide data directly to Home Assistant?

Thanks in advance for any help, I don't want to fry the wifi stick by doing this wrong!

**Comment by hn** [comment]
Everything you write is correct in principle (you just have to cross RX-TX lines, but that's a detail). But beware, this is a hackish project in its early stages, I can not guarantee anything). But I think you will not fry the stick.

Please also see #10.

For the serial adapter, I think a [cheaper one](https://www.amazon.co.uk/dp/B09F6GZGX6/) should do the job better.

**Comment by jonnyrider** [comment]
Thanks for the quick response!

I was originally going to create my own stick following this: https://github.com/incub77/solis2mqtt which is why I ordered that serial adapter. I will give it a go with that first (it arrives later) and if it doesn't work I'll try the adapter you mentioned.

**Comment by jonnyrider** [comment]
I tried this last night, but couldn't get the device to boot into the flash memory. I think I've got the wires round the wrong way, can you please help with where each wire should go when connected to the below?

![image](https://github.com/hn/ginlong-solis/assets/48350560/37fed67b-a996-471e-a631-f6739702ff78)

Thanks!

**Comment by hn** [comment]
I think you can not use this adapter. You need a 5V pin to power the stick (VCC).

**Comment by hn** [comment]
Please also see https://github.com/hn/ginlong-solis/issues/9#issuecomment-1595643051

**Comment by jonnyrider** [comment]
Thanks, I've bought a new usb stick for this, but it only seems to boot up
the stick randomly. Probably something I'm doing, so will keep looking into
this!
