### ISSUE TITLE
Solis smart meter support

### ISSUE THREAD

**Issue by air-fuel-ratio** [hn/ginlong-solis#19]
I cant see anything relating to the smart meter, does this support reading from the smart meter plugged into the inverter?

**Comment by hn** [comment]
I do not have such a setup. Which smart meter do you mean, how is it connected to the Inverter?

In [RS485_MODBUS (INV-3000IDEPM-36000ID) inverter protocol](https://ginlongsolis.freshdesk.com/helpdesk/attachments/36112313359) (or [this document for ESINV type]( https://forum.iobroker.net/assets/uploads/files/1619515984065-_without-control-hybrid-en-2020.9.15_rs485_modbus-esinv-33000id-hybrid-inverter.pdf) inverters) you see that there are lots of registers (starting at 3250, but also others), so it should be no problem to read data from a meter.

It is _probably_ the same as reading data from a BMS.

**Comment by hn** [comment]
From what I read in the documentation, it should be easy to add the ports to the ModBus Yaml file and get the readings. As I said, I think it works the same as getting the battery BMS values.

Please report back if you or others have any practical experience with this or are willing to test such a configuration.
