### ISSUE TITLE
High values for Active Power

### ISSUE THREAD

**Issue by ErwinP** [hn/ginlong-solis#26]
Hi,

I have an Solis RHI-5K-48ES-5G, and I'm using a wifi stick flashed with the latest firmware (as discussed [here](https://github.com/hn/ginlong-solis/issues/23)), and I'm having these strange values for "Active Power":
![image](https://github.com/hn/ginlong-solis/assets/1286494/9a429fd9-f772-4c8f-b4fb-9046d325ca7d).

I can try to templatize this to remove these peaks, but was wondering if anyone else has seen this as well?

Thanks,
Erwin

**Comment by hn** [comment]
I do not have access to an ESINV inverter, so the yaml was written without any testing (likely I just copied it from the INV yaml).

From [the spec](https://forum.iobroker.net/assets/uploads/files/1619515984065-_without-control-hybrid-en-2020.9.15_rs485_modbus-esinv-33000id-hybrid-inverter.pdf) one can see that register 33079 "Active Power" is a S32 value.

You might want to change

```
    name: Active Power
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    register_type: read
    address: 33079
    value_type: U_DWORD
```

to an `S_DWORD` ([docs here](https://esphome.io/components/sensor/modbus_controller)). Negative values with the high bits set might produce high values if casted to uint.
