### ISSUE TITLE
ESPHome missing sensors versus SolisCloud integration

### ISSUE THREAD

**Issue by TheGroundZero** [hn/ginlong-solis#28]
I'm (currently) not using many sensors that the inverter provides, but I noticed there is a difference between what I used to get from SolisCloud versus what ESPHome now reports.

SolisCloud / ESPHome
![SolisCloud](https://github.com/hn/ginlong-solis/assets/2406013/d8d24d69-6861-46f1-a96b-525525f5d09b)![ESPHome](https://github.com/hn/ginlong-solis/assets/2406013/69bf1bd2-344b-4e3b-b558-204d6116ed32)

Notably, I appear to be missing the `Solis AC Output Total Power` which depicts my solar production, and `Solis Battery Power` which shows me power flowing to/from the battery.
Unless that's what `Total DC output power` is supposed to report? It's reporting 0W while I would expect to still be drawing power from my battery as it's still 45% full.
`Active Power` perhaps? Or does that include solar?

Also, somehow the Solis integration was reporting 2493kWh of Total Energy produced, while ESPHome now "only" reports 2486kWh?
I did, shortly, have a different Solis inverter before it got replaced with my current, so maybe the first only produced 7kWh and the SolisCloud integration is reporting the sum of the 2 although it created 2 devices for the 2 inverters?

**Comment by TheGroundZero** [comment]
> Maybe the [ModBus register map](https://github.com/hn/ginlong-solis?tab=readme-ov-file#solis-modbus-register-map-and-rs-485-documentation) helps to understand the meaning of specific values -- or to add more registers. I do not own an ESINV type inverter.

OK, got it. `Total DC output power` is PV production.
![image](https://github.com/hn/ginlong-solis/assets/2406013/bb08a9b8-21f0-4679-8ef0-d6a18a0dc1b7)

These look interesting for monitoring my battery:
![image](https://github.com/hn/ginlong-solis/assets/2406013/83937645-d3d1-4022-8973-5ddfa0c7018b)
![image](https://github.com/hn/ginlong-solis/assets/2406013/9f5069a5-0058-47bc-a1e6-72f32fc9893f)

**Comment by hn** [comment]
The [invert filter](https://esphome.io/components/binary_sensor/index.html#invert) may help.

Please feel free to submit a reasonable set of additional sensors for inclusion into the ESINV yaml when you have completed your tests and you are convinced that the values are relevant to most users.

**Comment by TheGroundZero** [comment]
Some of these I disabled in the ESPHome code already (can be nade available on-demand), others I've disabled myself because I don't actively monitor them

![image](https://github.com/hn/ginlong-solis/assets/2406013/1d287c64-8c3b-4d26-9441-65345ae1251f)
