### ISSUE TITLE
ltchiptool upload error "Not a valid FlashMode"

### ISSUE THREAD

**Issue by isu-r** [hn/ginlong-solis#30]
Hello,

I successfully dumped the original firmware from the Datalogger Model S3 and have been experimented with various codes using PlatformIO. Uploading codes to the chip has been smooth without any issues.

But, I encountered an error when attempting to flash the firmware file generated using ESPHome as the instructions. As I'm new to ESPHome,
![Screenshot_4](https://github.com/hn/ginlong-solis/assets/156162822/fdd03829-6388-4239-b216-09dcde8fe1b4)
I hope this data is enough for troubleshooting.

Thank you!

**Comment by hn** [comment]
Don't know what 'Not a valid FlashMode' means, you'll have to ask the ltchiptool maintainers. I never experienced that kind of error.

Maybe it's an option to flash the XIP binaries (choose 'Download OTA1/2 XIP image' within ESPHome) like this (not tested at all!):

```
$ ltchiptool flash write -d /dev/ttyUSB0 -f realtek-ambz -s 0xb000 solis-emw3080-0x00B000.bin
$ ltchiptool flash write -d /dev/ttyUSB0 -f realtek-ambz -s 0x100000 solis-emw3080-0x100000.bin
```

**Comment by isu-r** [comment]
> Don't know what 'Not a valid FlashMode' means, you'll have to ask the ltchiptool maintainers. I never experienced that kind of error.
> 
> Maybe it's an option to flash the XIP binaries (choose 'Download OTA1/2 XIP image' within ESPHome) like this (not tested at all!):
> 
> ```
> $ ltchiptool flash write -d /dev/ttyUSB0 -f realtek-ambz -s 0xb000 solis-emw3080-0x00B000.bin
> $ ltchiptool flash write -d /dev/ttyUSB0 -f realtek-ambz -s 0x100000 solis-emw3080-0x100000.bin
> ```

Hello. Thank you for the reply! I had tried flashing using this method, but it didn't work properly. After multiple attempts, I rewrote the original dump, but it also failed. After several rounds of testing, I found that I needed to write:

1st original dump,
2nd solis-emw3080-0x100000.bin,
3rd solis-emw3080-0x00B000.bin.

Now it is working :)

I also need to mention that the firmware didn't find and connect to hidden networks; it only connects to networks that broadcast SSID
