### ISSUE TITLE
Limited output power

### ISSUE THREAD

**Issue by remco-h** [hn/ginlong-solis#31]
Hi, I build the configuration for the esp version with an ESP32. I get al the data but it is not possible to limit the output power from my solis S6-GR1P4K converter.

In HA is a message: this entity is switch off. Is there a way to enable this function? 
![Screenshot_2024-05-12-10-28-14-24_c3a231c25ed346e59462e84656a70e50](https://github.com/hn/ginlong-solis/assets/79400763/60c404f8-d4e5-4307-ab42-dcc11a4144c1)

**Comment by hn** [comment]
The setting ist disabled by default by intention. You can enable it

- [via the HA GUI](https://esphome.io/components/number/index.html) "disabled_by_default" I do not rembember how to do it, maybe double clicking?
- by removing [the line in the yaml](https://github.com/hn/ginlong-solis/blob/36f63b92578a4d8e55b6328a52a4fccd2ebed221/solis-modbus-inv.yaml#L30C5-L30C24)
