### ISSUE TITLE
Exceedconn EC04681-2014-BF connector 3D models

### ISSUE THREAD

**Issue by nextguyover** [hn/ginlong-solis#37]
I recently [did a writeup](https://insertnewline.com/blog/Solis-solar-esphome/) of my own implementation of ESPHome on my Solis PV system, where I 3D modelled and printed the Exceedconn EC04681-2014-BF connector.

Since this is a much cheaper alternative to purchasing the connector, or purchasing a new Wi-Fi stick altogether, I thought this might be a useful resource to reference here as well.

I have made download links for 3D models of the connector (and an enclosure) available at the blogpost above (plus instructions for 3D printing and forming the contacts for the connector). If you think this would be useful, feel free to link the blogpost from the readme.

Alternatively, I'm also happy for you to include the 3D model files directly on this repo with attribution, let me know if you would like me to make a PR. 

Thanks again for the work you've done with reverse engineering this, it has been very useful 🙂.

**Comment by hn** [comment]
Thanks for sharing! I'm always happy to see what great projects people all over the world develop based on my work.

As you have described your project so comprehensively and in such detail, I will be pleased to link to it. Just copying the 3D models here would be a loss of information.
