### ISSUE TITLE
MQTT support for RTL87xx boards

### ISSUE THREAD

**Issue by namsral** [hn/ginlong-solis#43]
A feature request to support publishing Solis inverter metrics to MQTT brokers for RTL87XX boards.

I have Solis S3 WiFi stick with the newer emw3080 pcb and compiling the MQTT client in ESPHome fails:

```
% esphome compile solis-esphome-emw3080.yaml
INFO ESPHome 2024.6.6
INFO Reading configuration solis-esphome-emw3080.yaml...
Failed config

mqtt: [source solis-esphome-emw3080.yaml:164]

  This feature is only available on ['esp32', 'esp8266', 'bk72xx'].
  broker: 192.168.1.100
  port: 8883
```

**Comment by hn** [comment]
Unfortunately, this is not possible within the scope of this project. You will have to address your request to the [esphome](https://github.com/esphome/feature-requests/issues) or [LibretTiny](https://github.com/libretiny-eu/libretiny) project.
