### ISSUE TITLE
Modbus TCP IP Proxy 

### ISSUE THREAD

**Issue by deadrabbit87** [hn/ginlong-solis#45]
Hi, 

I'm not sure if this is the right place for my feature request.

Does anyone knows, if it is possible to add an Modbus TCP IP Proxy to esphome?

Thanks! 

BW

**Comment by hn** [comment]
Unfortunately that‘s out of scope for this project. Maybe https://github.com/esphome/feature-requests/issues/1992 is a good starting point for that feature.
