### ISSUE TITLE
How to configure Remote server B

### ISSUE THREAD

**Issue by KhurramFHassan** [hn/ginlong-solis#47]
I have just installed a Solis S5 inverter along with it dongle. I have noticed on the dongle's web status page that there is an option for a "Remote Server B" but it is shown as unconfigured. How can I configure it to send data to another device on my network?

Thanks

![00 Status - Remote Server Information](https://github.com/user-attachments/assets/770bdcd9-1a49-40d7-8c17-717c9a77085b)

**Comment by hn** [comment]
https://github.com/hn/ginlong-solis?tab=readme-ov-file#software

> The firmware (at least the current version 1012F) is a kind of beta and incomplete, as it lacks important functions that are available in the previous generation WiFi sticks. In particular, support for setting a second remote logging server (called "Server B") is missing.
