### ISSUE TITLE
Error on esphome

### ISSUE THREAD

**Issue by Tangiers2020** [hn/ginlong-solis#49]
Hi, i am getting an error when trying to install via esphome.

Error reading file /config/esphome/common/solis-modbus-esinv.yaml: [Errno 2] No such file or directory: '/config/esphome/common/solis-modbus-esinv.yaml'

This happens when i uncomment the esinv: !include common/solis-modbus-esinv.yaml packadge

**Comment by hn** [comment]
You have to move `solis-modbus-esinv.yaml` to a subdirectory called `common`.
