### ISSUE TITLE
Update frequency using Solis WiFi stick

### ISSUE THREAD

**Issue by JGeeforce** [hn/ginlong-solis#50]
Just a question before I will flash my Solis WiFi stick.  How often is HA getting the values from the stick? With the cloud it's every five minutes, but if it is realtime, every second, the DB from HA will grow very fast. Seen that with P1 meter too.

**Comment by hn** [comment]
It is possible (not recommended) to [change the update interval](https://esphome.io/components/modbus_controller.html#configuration-variables) from default (60 seconds).

Not specific to this project: If your HA database is growing to big, [change data retention settings](https://www.home-assistant.io/integrations/recorder/#configure-filter). Not needed for the Solis stick.
