### ISSUE TITLE
How to get more sensors?

### ISSUE THREAD

**Issue by JGeeforce** [hn/ginlong-solis#51]
First of all, thank you for this project. had some issues backing up the original firmware, until I set the baud rate to auto, so a tip for other.

When using the Solis cloud within HA I have much more sensors, which seems to be "missing" in this ESP project. Is it possible to add more by adding them to the yaml code? And is there an overview of what their name is?

**Comment by hn** [comment]
Please contribute back and post all learnings (baud rate, ...) you had to the [beginners guide](https://github.com/hn/ginlong-solis/issues/48)

Check the [ModBus register maps](https://github.com/hn/ginlong-solis?tab=readme-ov-file#solis-modbus-register-map-and-rs-485-documentation) if you want to add more values.
